"""Music bed and sound design, synthesised from scratch.

Everything here is generated by this file, so there is no licensing question to
answer and nothing to credit.  The brief for the mix: narration is king, the bed
sits far underneath, and none of it should sound like an action trailer.

Levels (relative to the narration peak at -1 dBFS):
  narration   0 dB     - untouched, only peak-normalised
  music bed  -22 dB    - sub drone + slow pad, ducked further under speech
  SFX        -16 dB    - short, sparse, mixed to taste per cue
"""
from __future__ import annotations

import math

import numpy as np

SR = 48000


def _t(n):
    return np.arange(n, dtype=np.float32) / SR


def _env(n, attack, release, sustain=1.0):
    e = np.full(n, sustain, dtype=np.float32)
    a = min(int(attack * SR), n)
    r = min(int(release * SR), n - a) if n > a else 0
    if a:
        e[:a] *= np.linspace(0, 1, a, dtype=np.float32)
    if r:
        e[n - r:] *= np.linspace(1, 0, r, dtype=np.float32)
    return e


def _lp(x, cutoff):
    """One-pole low pass - enough to take the edge off synthetic tones."""
    a = math.exp(-2 * math.pi * cutoff / SR)
    y = np.empty_like(x)
    acc = 0.0
    for i in range(len(x)):
        acc = (1 - a) * x[i] + a * acc
        y[i] = acc
    return y


def _lp_fast(x, cutoff):
    """Vectorised approximation of the above via repeated box smoothing."""
    k = max(1, int(SR / max(cutoff, 1) / 2))
    if k <= 1:
        return x
    c = np.cumsum(np.concatenate([[0.0], x.astype(np.float64)]))
    y = (c[k:] - c[:-k]) / k
    return np.concatenate([x[: len(x) - len(y)], y.astype(np.float32)])


# ------------------------------------------------------------------- music
def music_bed(duration, scene_times):
    """A slow, dark pad: a sub fundamental, two fifths, and a very slow filter
    drift.  Deliberately static - it is a floor for the voice, not a tune."""
    n = int(duration * SR)
    t = _t(n)
    out = np.zeros(n, dtype=np.float32)

    root = 55.0  # A1
    # sub + harmonics, each detuned slightly so it never sounds like a synth pad
    for mult, amp, detune in ((1.0, 0.50, 0.0), (1.5, 0.16, 0.13),
                              (2.0, 0.20, -0.09), (3.0, 0.075, 0.21),
                              (4.0, 0.045, -0.17)):
        f = root * mult + detune
        drift = 1.0 + 0.0016 * np.sin(2 * math.pi * 0.032 * t + mult)
        out += amp * np.sin(2 * math.pi * f * t * drift).astype(np.float32)

    # a breathing motion so the bed is not dead flat
    out *= (0.72 + 0.28 * np.sin(2 * math.pi * 0.055 * t - 1.1)).astype(np.float32)

    # air: filtered noise, very quiet
    rng = np.random.default_rng(4242)
    air = _lp_fast(rng.normal(0, 1, n).astype(np.float32), 900)
    air = _lp_fast(air, 420)
    out += air * 0.16

    # lift the bed a touch at each act change so the edit has some shape
    for st in scene_times:
        i = int(st * SR)
        ln = int(1.4 * SR)
        if i + ln > n:
            continue
        out[i:i + ln] *= (1.0 + 0.30 * _env(ln, 0.25, 1.1, 1.0)).astype(np.float32)

    peak = float(np.abs(out).max()) or 1.0
    return (out / peak).astype(np.float32)


# --------------------------------------------------------------------- SFX
def radar_ping(dur=1.1, f=1480.0):
    n = int(dur * SR)
    t = _t(n)
    y = np.sin(2 * math.pi * f * t) * np.exp(-t * 7.5)
    y += 0.4 * np.sin(2 * math.pi * f * 1.5 * t) * np.exp(-t * 11.0)
    # a short tail so it reads as a room, not a beep
    tail = np.exp(-t * 2.2) * np.sin(2 * math.pi * f * 0.5 * t) * 0.18
    return ((y + tail) * _env(n, 0.002, dur * 0.7)).astype(np.float32) * 0.5


def ui_blip(dur=0.16, f=2100.0):
    n = int(dur * SR)
    t = _t(n)
    y = np.sin(2 * math.pi * f * t) * np.exp(-t * 34)
    return (y * _env(n, 0.001, 0.05)).astype(np.float32) * 0.34


def drone_hum(dur, f=118.0, seed=1):
    """Rotor-ish tone: a low fundamental with a blade-rate flutter on top."""
    n = int(dur * SR)
    t = _t(n)
    rng = np.random.default_rng(seed)
    y = np.sin(2 * math.pi * f * t) * 0.55
    y += np.sin(2 * math.pi * f * 2.02 * t) * 0.22
    y *= (1.0 + 0.30 * np.sin(2 * math.pi * 44.0 * t))          # blade flutter
    y += _lp_fast(rng.normal(0, 1, n).astype(np.float32), 1600) * 0.22
    return (y * _env(n, 0.5, 0.8)).astype(np.float32) * 0.30


def sweep_air(dur=1.0, seed=2):
    """Airspace scan: filtered noise swept upward.  Used at transitions."""
    n = int(dur * SR)
    t = _t(n)
    rng = np.random.default_rng(seed)
    nz = rng.normal(0, 1, n).astype(np.float32)
    y = _lp_fast(nz, 1200)
    y *= (t / max(t[-1], 1e-6)) ** 1.6
    y *= np.exp(-((t - dur * 0.82) / (dur * 0.30)) ** 2)
    return y.astype(np.float32) * 0.30


def impact(dur=1.5, f=44.0):
    """Soft transition hit - a filtered sub thud, no drum, no cymbal."""
    n = int(dur * SR)
    t = _t(n)
    y = np.sin(2 * math.pi * f * t * (1.0 + 2.2 * np.exp(-t * 26))) * np.exp(-t * 4.2)
    rng = np.random.default_rng(9)
    y += _lp_fast(rng.normal(0, 1, n).astype(np.float32), 220) * np.exp(-t * 16) * 0.35
    return (y * _env(n, 0.001, dur * 0.6)).astype(np.float32) * 0.62


# --------------------------------------------------------------------- mix
def place(bus, clip, at, gain=1.0):
    i = int(at * SR)
    if i < 0:
        clip = clip[-i:]
        i = 0
    j = min(len(bus), i + len(clip))
    if j <= i:
        return
    bus[i:j] += clip[: j - i] * gain


def duck(bed, narration, amount=0.55, attack=0.05, release=0.45):
    """Side-chain the bed to the narration envelope so speech always wins."""
    n = len(bed)
    v = np.abs(narration[:n])
    win = int(0.02 * SR)
    pad = (-len(v)) % win
    e = np.pad(v, (0, pad)).reshape(-1, win).max(axis=1)
    e = np.repeat(e, win)[:n]

    # asymmetric smoothing: fast to duck, slow to come back
    ka = math.exp(-1.0 / (attack * SR / win))
    kr = math.exp(-1.0 / (release * SR / win))
    sm = np.empty_like(e)
    acc = 0.0
    step = max(1, win // 4)
    for i in range(0, n, step):
        x = e[i]
        k = ka if x > acc else kr
        acc = x + k * (acc - x)
        sm[i:i + step] = acc
    sm = sm[:n]
    g = 1.0 - amount * np.clip(sm / 0.35, 0, 1)
    return bed * g.astype(np.float32)
